<?php echo $this->doctype();?>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
      /*add:fadeSlider*/->prependStylesheet($this->basePath() . '/css/fadeBsCarousel.css')
      /*add:time-line*/->prependStylesheet($this->basePath() . '/css/time-line.css')
      /*add:about-custom*/->prependStylesheet($this->basePath() . '/css/about.css')
      /*add:gallery*/->prependStylesheet($this->basePath() . '/css/gallery.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            //->prependFile($this->basePath() . '/js/multipleFieldsContact.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<?php echo 'Indexindex' == $CURRENT_ROUTE_VALID_MENU?'active':''; ?>"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Inicio') ?></a></li>
                         <li class="<?php echo 'Ensaioindex' == $CURRENT_ROUTE_VALID_MENU?'active':''; ?>"><a href="<?php echo $this->url('ensaio') ?>"><?php echo $this->translate('Ensaios') ?></a></li>
                        <li class="<?php echo 'Sobreindex' == $CURRENT_ROUTE_VALID_MENU?'active':''; ?>"><a href="<?php echo $this->url('sobre') ?>"><?php echo $this->translate('Sobre') ?></a></li>
                         <li class="<?php echo 'Contatoindex' == $CURRENT_ROUTE_VALID_MENU?'active':''; ?>"><a href="<?php echo $this->url('contato') ?>"><?php echo $this->translate('Contato') ?></a></li>
                       <li class="<?php echo 'Indexlogin' == $CURRENT_ROUTE_VALID_MENU?'active':''; ?>"><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <br/><br/><br/><br/>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by Liit Agency Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
