<div class="row-fluid">

    <div class="col-md-7">
        <div class="well well-sm">
          <form class="form-horizontal" action="" method="post">
          <fieldset>
            <legend class="text-center">Contact us</legend>
    
            <!-- Name input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name">Name</label>
              <div class="col-md-9">
                <input id="name" name="name" type="text" placeholder="Your name" class="form-control">
              </div>
            </div>
    
            <!-- Email input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="email">Your E-mail</label>
              <div class="col-md-9">
                <input id="email" name="email" type="text" placeholder="Your email" class="form-control">
              </div>
            </div>
    
            <!-- Message body -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="message">Your message</label>
              <div class="col-md-9">
                <textarea class="form-control" id="message" name="message" placeholder="Please enter your message here..." rows="5"></textarea>
              </div>
            </div>
    
            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-success btn-lg">Submit</button>
              </div>
            </div>
          </fieldset>
          </form>
        </div>
    </div>
    <div class="col-md-5">
        <h2>Contato</h2>
        <address>
            <strong>Hythe Window Cleaning</strong><br>
            15 Springfield Way<br>
            Hythe<br>
            <abbr title="Phone">P:</abbr> 01234 567 890
        </address>

        <div class="thumbnail center well well-small text-center">
            <h2>Newsletter</h2>
            
            <p>Subscribe to our weekly Newsletter and stay tuned.</p>
            
            <form action="" method="post">
                <div class="input-prepend"><span class="add-on"><i class="icon-envelope"></i></span>
                    <input type="text" id="" name="" placeholder="your@email.com">
                </div>
                <br />
                <input type="submit" value="Subscribe Now!" class="btn btn-large" />
          </form>
        </div>   

    </div>

    <div class="col-md-12">
        <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&source=s_q&hl=en&geocode=&q=15+Springfield+Way,+Hythe,+CT21+5SH&aq=t&sll=52.8382,-2.327815&sspn=8.047465,13.666992&ie=UTF8&hq=&hnear=15+Springfield+Way,+Hythe+CT21+5SH,+United+Kingdom&t=m&z=14&ll=51.077429,1.121722&output=embed"></iframe>
    </div>
</div>